### ISSUE TITLE
idk im on windows 11 and thats all i think is a problem

### ISSUE THREAD

**Issue by ghost** [GraxCode/JByteMod-Beta#100]
java.io.IOException: Access is denied
	at java.base/java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.base/java.io.File.createNewFile(File.java:1043)
	at me.grax.jbytemod.res.Options.lambda$save$1(Options.java:120)
	at java.base/java.lang.Thread.run(Thread.java:833)

Please report exceptions on github.

https://github.com/GraxCode/JByteMod-Beta

**Comment by ghost** [comment]
java.io.IOException: Access is denied
	at java.base/java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.base/java.io.File.createNewFile(File.java:1043)
	at me.grax.jbytemod.res.Options.lambda$save$1(Options.java:120)
	at java.base/java.lang.Thread.run(Thread.java:833)


Please report exceptions on github.

https://github.com/GraxCode/JByteMod-Beta

**Comment by neilhuang007** [comment]
me too
