### ISSUE TITLE
Access is denied error

### ISSUE THREAD

**Issue by fspofficial** [GraxCode/JByteMod-Beta#106]
java.io.IOException: Access is denied
	at java.base/java.io.WinNTFileSystem.createFileExclusively0(Native Method)
	at java.base/java.io.WinNTFileSystem.createFileExclusively(WinNTFileSystem.java:645)
	at java.base/java.io.File.createNewFile(File.java:1045)
	at me.grax.jbytemod.res.Options.lambda$1(Options.java:120)
	at java.base/java.lang.Thread.run(Thread.java:1623

**Comment by 15ggd** [comment]
java.io.IOException: Access is denied
	at java.base/java.io.WinNTFileSystem.createFileExclusively0(Native Method)
	at java.base/java.io.WinNTFileSystem.createFileExclusively(WinNTFileSystem.java:536)
	at java.base/java.io.File.createNewFile(File.java:1045)
	at me.grax.jbytemod.res.Options.lambda$save$1(Options.java:120)
	at java.base/java.lang.Thread.run(Thread.java:1583)


same error different threads?
