### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by yKsenomorf** [GraxCode/JByteMod-Beta#29]
This happens at JByteMod 1.6.1.
Stacktrace:
PS C:\Users\Admin\Desktop\JByteMod-1.6.0> java -jar .\JByteMod-1.6.1.jar
java.lang.UnsatisfiedLinkError: no attach in java.library.path
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.lang.System.loadLibrary(Unknown Source)
        at me.grax.jbytemod.JByteMod.<clinit>(JByteMod.java:102)
[15:46:03] [INFO] Reading Language XML..
Exception in thread "main" java.lang.NullPointerException
        at me.grax.jbytemod.utils.ErrorDisplay._init_(ErrorDisplay.java:51)
        at me.grax.jbytemod.utils.ErrorDisplay.<init>(ErrorDisplay.java:27)
        at me.grax.jbytemod.res.LanguageRes.readXML(LanguageRes.java:49)
        at me.grax.jbytemod.res.LanguageRes.<init>(LanguageRes.java:24)
        at me.grax.jbytemod.JByteMod.initialize(JByteMod.java:110)
        at me.grax.jbytemod.JByteMod.main(JByteMod.java:149)
PS C:\Users\Admin\Desktop\JByteMod-1.6.0>

**Comment by GraxCode** [comment]
problem was the encoding of the russian language, fixed it in the latest commit

**Comment by GraxCode** [comment]
https://github.com/GraxCode/JByteMod-Beta/releases/tag/1.6.2
