### ISSUE TITLE
Failed loading class file - java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by Hdadaw** [GraxCode/JByteMod-Beta#48]
Very strange compilled classes of this resource cannot be opened in jbytemod:
https://github.com/bristik/AdvancedCommandBlocker/releases

```
[11:57:38] [INFO] Reading Language XML..
[11:57:38] [INFO] Successfully loaded 87 local resources and 87 default resources
[11:57:38] [INFO] Unicode check finished!
[11:57:38] [INFO] Loading settings...
[11:57:38] [INFO] Setting default Look and Feel
[11:57:40] [INFO] 1 plugin(s) loaded!
[11:57:41] [INFO] 17 files to load!
java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:159)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:142)
        at me.lpk.util.ASMUtils.getNode(ASMUtils.java:42)
        at me.grax.jbytemod.utils.task.LoadTask.readJar(LoadTask.java:99)
        at me.grax.jbytemod.utils.task.LoadTask.lambda$0(LoadTask.java:82)
        at java.util.Iterator.forEachRemaining(Unknown Source)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
        at me.grax.jbytemod.utils.task.LoadTask.loadFiles(LoadTask.java:82)
        at me.grax.jbytemod.utils.task.LoadTask.doInBackground(LoadTask.java:54)
        at me.grax.jbytemod.utils.task.LoadTask.doInBackground(LoadTask.java:1)
        at javax.swing.SwingWorker$1.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at javax.swing.SwingWorker.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[11:57:42] [ERROR] Failed loading class file ru/bristol/advancedcommandblocker/AdvancedCommandBlocker.class
java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:159)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:142)
        at me.lpk.util.ASMUtils.getNode(ASMUtils.java:42)
        at me.grax.jbytemod.utils.task.LoadTask.readJar(LoadTask.java:99)
        at me.grax.jbytemod.utils.task.LoadTask.lambda$0(LoadTask.java:82)
        at java.util.Iterator.forEachRemaining(Unknown Source)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
        at me.grax.jbytemod.utils.task.LoadTask.loadFiles(LoadTask.java:82)
        at me.grax.jbytemod.utils.task.LoadTask.doInBackground(LoadTask.java:54)
        at me.grax.jbytemod.utils.task.LoadTask.doInBackground(LoadTask.java:1)
        at javax.swing.SwingWorker$1.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at javax.swing.SwingWorker.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[11:57:42] [ERROR] Failed loading class file ru/bristol/advancedcommandblocker/hooks/ChatHooks.class
java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:159)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:142)
        at me.lpk.util.ASMUtils.getNode(ASMUtils.java:42)
        at me.grax.jbytemod.utils.task.LoadTask.readJar(LoadTask.java:99)
        at me.grax.jbytemod.utils.task.LoadTask.lambda$0(LoadTask.java:82)
        at java.util.Iterator.forEachRemaining(Unknown Source)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
        at me.grax.jbytemod.utils.task.LoadTask.loadFiles(LoadTask.java:82)
        at me.grax.jbytemod.utils.task.LoadTask.doInBackground(LoadTask.java:54)
        at me.grax.jbytemod.utils.task.LoadTask.doInBackground(LoadTask.java:1)
        at javax.swing.SwingWorker$1.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at javax.swing.SwingWorker.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[11:57:42] [ERROR] Failed loading class file ru/bristol/advancedcommandblocker/managers/BCommandManager.class
java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:159)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:142)
        at me.lpk.util.ASMUtils.getNode(ASMUtils.java:42)
        at me.grax.jbytemod.utils.task.LoadTask.readJar(LoadTask.java:99)
        at me.grax.jbytemod.utils.task.LoadTask.lambda$0(LoadTask.java:82)
        at java.util.Iterator.forEachRemaining(Unknown Source)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
        at me.grax.jbytemod.utils.task.LoadTask.loadFiles(LoadTask.java:82)
        at me.grax.jbytemod.utils.task.LoadTask.doInBackground(LoadTask.java:54)
        at me.grax.jbytemod.utils.task.LoadTask.doInBackground(LoadTask.java:1)
        at javax.swing.SwingWorker$1.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at javax.swing.SwingWorker.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[11:57:42] [ERROR] Failed loading class file ru/bristol/advancedcommandblocker/managers/ConfigManager.class
java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:159)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:142)
        at me.lpk.util.ASMUtils.getNode(ASMUtils.java:42)
        at me.grax.jbytemod.utils.task.LoadTask.readJar(LoadTask.java:99)
        at me.grax.jbytemod.utils.task.LoadTask.lambda$0(LoadTask.java:82)
        at java.util.Iterator.forEachRemaining(Unknown Source)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
        at me.grax.jbytemod.utils.task.LoadTask.loadFiles(LoadTask.java:82)
        at me.grax.jbytemod.utils.task.LoadTask.doInBackground(LoadTask.java:54)
        at me.grax.jbytemod.utils.task.LoadTask.doInBackground(LoadTask.java:1)
        at javax.swing.SwingWorker$1.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at javax.swing.SwingWorker.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[11:57:42] [ERROR] Failed loading class file ru/bristol/advancedcommandblocker/types/BType.class
java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:159)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:142)
        at me.lpk.util.ASMUtils.getNode(ASMUtils.java:42)
        at me.grax.jbytemod.utils.task.LoadTask.readJar(LoadTask.java:99)
        at me.grax.jbytemod.utils.task.LoadTask.lambda$0(LoadTask.java:82)
        at java.util.Iterator.forEachRemaining(Unknown Source)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
        at me.grax.jbytemod.utils.task.LoadTask.loadFiles(LoadTask.java:82)
        at me.grax.jbytemod.utils.task.LoadTask.doInBackground(LoadTask.java:54)
        at me.grax.jbytemod.utils.task.LoadTask.doInBackground(LoadTask.java:1)
        at javax.swing.SwingWorker$1.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at javax.swing.SwingWorker.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[11:57:42] [ERROR] Failed loading class file ru/bristol/advancedcommandblocker/utils/Utils.class
java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:159)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:142)
        at me.lpk.util.ASMUtils.getNode(ASMUtils.java:42)
        at me.grax.jbytemod.utils.task.LoadTask.readJar(LoadTask.java:99)
        at me.grax.jbytemod.utils.task.LoadTask.lambda$0(LoadTask.java:82)
        at java.util.Iterator.forEachRemaining(Unknown Source)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
        at me.grax.jbytemod.utils.task.LoadTask.loadFiles(LoadTask.java:82)
        at me.grax.jbytemod.utils.task.LoadTask.doInBackground(LoadTask.java:54)
        at me.grax.jbytemod.utils.task.LoadTask.doInBackground(LoadTask.java:1)
        at javax.swing.SwingWorker$1.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at javax.swing.SwingWorker.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[11:57:42] [ERROR] Failed loading class file ru/bristol/advancedcommandblocker/variables/BCommand.class
[11:57:42] [INFO] Successfully loaded file!
[11:57:42] [INFO] Building tree..
```

**Comment by GraxCode** [comment]
JByteMod does currently not support java 10, you can try removing ClassReader#159, but I cannot guarantee that it will work
