### ISSUE TITLE
java.io.IOException: Cannot run program ""/usr/bin/python3""

### ISSUE THREAD

**Issue by xor-shift** [GraxCode/JByteMod-Beta#52]
This error is produced when trying to use krakatau for bytecode editing with the provided python directory: /usr/bin/python3  
  
The provided directory has no quotes in it and there is a file called python3 in /usr/bin/.  
  
```  
java.io.IOException: Cannot run program ""/usr/bin/python3"": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at me.grax.jbytemod.decompiler.KrakatauDecompiler.decompile(KrakatauDecompiler.java:45)
	at me.grax.jbytemod.decompiler.Decompiler.decompile(Decompiler.java:53)
	at me.grax.jbytemod.decompiler.Decompiler.run(Decompiler.java:41)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 6 more


Please try setting the python path  
```

**Comment by GraxCode** [comment]
Please try without /usr/bin (only "python3") as the path

**Comment by Daswf852** [comment]
Now I'm getting the following:  
```java.io.IOException: Cannot run program "py": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at me.grax.jbytemod.decompiler.KrakatauDecompiler.decompile(KrakatauDecompiler.java:45)
	at me.grax.jbytemod.decompiler.Decompiler.decompile(Decompiler.java:53)
	at me.grax.jbytemod.decompiler.Decompiler.run(Decompiler.java:41)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 6 more


Please try setting the python path
```

**Comment by tegid77** [comment]
@Daswf852 where you ever able to correct this issue?  I am experiencing this same issue now and I am not finding much documentation as to fixing it.

**Comment by dean-vanwyk-impact** [comment]
@tegid77 I ran into this problem now and found that my specific issue was that I had python 2.7 configured as my Python SDK in my project. It was resolved when I upgraded to python3.8

**Comment by sjtuzhaoxh** [comment]
我的问题还在
