### ISSUE TITLE
Java -jar JByteMod-1.8.1.jar Error: 

### ISSUE THREAD

**Issue by mancong** [GraxCode/JByteMod-Beta#60]
Java version "1.8.0_131" running has the following problem
[19:53:51] [INFO] Reading Language XML..
[19:53:51] [INFO] Successfully loaded 85 local resources and 89 default resources
[19:53:51] [INFO] Updated WebLaF fonts for unicode support
[19:53:51] [INFO] Loading settings...
[19:53:51] [INFO] Setting default Look and Feel
[AWT-EventQueue-0] ERROR com.alee.utils.LafUtils - Unable to initialize L&F for class name: com.alee.laf.WebLookAndFeel
java.lang.ExceptionInInitializerError
        at com.alee.utils.ImageUtils.createGrayscaleCopy(ImageUtils.java:1229)
        at com.alee.utils.ImageUtils.createGrayscaleCopy(ImageUtils.java:1224)
        at com.alee.utils.ImageUtils.createDisabledCopy(ImageUtils.java:1202)
        at com.alee.utils.ImageUtils.createDisabledCopy(ImageUtils.java:1197)
        at com.alee.laf.tree.WebTreeUI.<clinit>(WebTreeUI.java:58)
        at com.alee.laf.WebLookAndFeel.initComponentDefaults(WebLookAndFeel.java:581)
        at javax.swing.plaf.basic.BasicLookAndFeel.getDefaults(BasicLookAndFeel.java:148)
        at javax.swing.UIManager.setLookAndFeel(UIManager.java:539)
        at javax.swing.UIManager.setLookAndFeel(UIManager.java:583)
        at com.alee.utils.LafUtils.setupLookAndFeelSafely(LafUtils.java:1557)
        at com.alee.utils.LafUtils.setupLookAndFeelSafely(LafUtils.java:1544)
        at com.alee.laf.WebLookAndFeel.install(WebLookAndFeel.java:939)
        at com.alee.laf.WebLookAndFeel.install(WebLookAndFeel.java:927)
        at me.grax.jbytemod.utils.gui.LookUtils.setLAF(LookUtils.java:15)
        at me.grax.jbytemod.JByteMod$1.run(JByteMod.java:170)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.IllegalArgumentException: Can't load standard profile: GRAY.pf
        at java.awt.color.ICC_Profile$2.run(ICC_Profile.java:935)
        at java.awt.color.ICC_Profile$2.run(ICC_Profile.java:929)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.awt.color.ICC_Profile.getStandardProfile(ICC_Profile.java:928)
        at java.awt.color.ICC_Profile.getDeferredInstance(ICC_Profile.java:1075)
        at java.awt.color.ICC_Profile.getInstance(ICC_Profile.java:895)
        at java.awt.color.ColorSpace.getInstance(ColorSpace.java:333)
        at com.alee.utils.ImageFilterUtils.<clinit>(ImageFilterUtils.java:59)
        ... 29 more
java.lang.NullPointerException
        at javax.swing.MultiUIDefaults.getUIError(MultiUIDefaults.java:130)
        at javax.swing.UIDefaults.getUI(UIDefaults.java:760)
        at javax.swing.UIManager.getUI(UIManager.java:1016)
        at javax.swing.JPanel.updateUI(JPanel.java:126)
        at javax.swing.JPanel.<init>(JPanel.java:86)
        at javax.swing.JPanel.<init>(JPanel.java:109)
        at javax.swing.JPanel.<init>(JPanel.java:117)
        at javax.swing.JRootPane.createGlassPane(JRootPane.java:546)
        at javax.swing.JRootPane.<init>(JRootPane.java:366)
        at javax.swing.JFrame.createRootPane(JFrame.java:286)
        at javax.swing.JFrame.frameInit(JFrame.java:267)
        at javax.swing.JFrame.<init>(JFrame.java:190)
        at me.grax.jbytemod.JByteMod.<init>(JByteMod.java:195)
        at me.grax.jbytemod.JByteMod$1.run(JByteMod.java:173)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by GraxCode** [comment]
Please submit your issue here: https://github.com/mgarin/weblaf
