### ISSUE TITLE
java.io.IOException: access denied 

### ISSUE THREAD

**Issue by mypsp2008** [GraxCode/JByteMod-Beta#68]
when startup,I got  this error as follow:
java.io.IOException: access denied 。
	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(Unknown Source)
	at me.grax.jbytemod.res.Options.lambda$1(Options.java:120)
	at java.lang.Thread.run(Unknown Source)

**Comment by GraxCode** [comment]
start jbytemod as administrator
