### ISSUE TITLE
Exception in thread "Thread-0" java.lang.NoClassDefFoundError: sun/misc/URLClassPath

### ISSUE THREAD

**Issue by AxDSan** [GraxCode/JByteMod-Beta#7]
```
Building tree..
Exception in thread "Thread-0" java.lang.NoClassDefFoundError: sun/misc/URLClassPath
        at com.strobel.assembler.metadata.ClasspathTypeLoader.<init>(ClasspathTypeLoader.java:66)
        at com.strobel.assembler.metadata.ClasspathTypeLoader.<init>(ClasspathTypeLoader.java:42)
        at com.strobel.assembler.metadata.MetadataSystem.<init>(MetadataSystem.java:48)
        at com.strobel.assembler.metadata.MetadataSystem.instance(MetadataSystem.java:40)
        at com.strobel.assembler.metadata.PrimitiveType.<init>(PrimitiveType.java:28)
        at com.strobel.assembler.metadata.BuiltinTypes.<clinit>(BuiltinTypes.java:40)
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unknown Source)
        at jdk.unsupported/sun.misc.Unsafe.ensureClassInitialized(Unknown Source)
        at com.strobel.compilerservices.RuntimeHelpers.ensureClassInitialized(RuntimeHelpers.java:31)
        at com.strobel.assembler.metadata.MetadataSystem.<clinit>(MetadataSystem.java:147)
        at me.grax.jbytemod.decompiler.DecompileThread.decompile(DecompileThread.java:51)
        at me.grax.jbytemod.decompiler.DecompileThread.run(DecompileThread.java:39)
Caused by: java.lang.ClassNotFoundException: sun.misc.URLClassPath
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 13 more
```

This happened to me now, whereas before it wasn't doing any of that, don't know what's causing it, I think I got a Java update not long ago but not really sure.

Issue: Just loaded a Jar for decompilation, when I expanded a class and wanted to access such class for decompilation it threw that exception

**Comment by GraxCode** [comment]
Procyon is currently incompatible with java 9, you'll need to downgrade to 8 to use the decompiler
