### ISSUE TITLE
java.io.IOException: Access is denied

### ISSUE THREAD

**Issue by mrhoangeg** [GraxCode/JByteMod-Beta#89]
at java.base/java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.base/java.io.File.createNewFile(File.java:1025)
	at me.grax.jbytemod.res.Options.lambda$1(Options.java:120)
	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by AquaNot** [comment]
java.io.IOException: Access is denied
	at java.base/java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.base/java.io.File.createNewFile(File.java:1034)
	at me.grax.jbytemod.res.Options.lambda$1(Options.java:93)
	at java.base/java.lang.Thread.run(Thread.java:831)


Please report exceptions on github.

https://github.com/GraxCode/JByteMod-Beta
