### ISSUE TITLE
Another error when loading it with bat file :/

### ISSUE THREAD

**Issue by StankToilet20388** [GraxCode/JByteMod-Beta#97]
at java.base/java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.base/java.io.File.createNewFile(File.java:1043)
	at me.grax.jbytemod.res.Options.lambda$1(Options.java:120)
	at java.base/java.lang.Thread.run(Thread.java:833)

this was the error I got :( idk what is up with this program

**Comment by asamikiyomi** [comment]
stupid.. you don't have to run it with bat file , just click on the jar directly
