### ISSUE TITLE
Hello, i have this problem.. please help

### ISSUE THREAD

**Issue by ttngr05** [GraxCode/JByteMod-Beta#98]
java.io.IOException: Přístup byl odepřen
	at java.base/java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.base/java.io.File.createNewFile(File.java:1034)
	at me.grax.jbytemod.res.Options.lambda$1(Options.java:120)
	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by ghost** [comment]
me to!
